package functions

var Keys = keys{
	First:             "first",
	Not:               "not",
	SignalNot:         "signal_not",
	SignalExclamation: "signal_!",
	SignalAdd:         "signal_+",
	SignalSub:         "signal_-",
	DoubleSub:         "--",
	Add:               "+",
	Sub:               "-",
	Mul:               "*",
	Div:               "/",
	Res:               "%",
	Exist:             "exist",
	Is:                "is",
	IsNot:             "is_not",
	In:                "in",
	NotIn:             "not_in",
	Or:                "or",
	And:               "and",
	Equal:             "=",
	GreaterEqual:      ">=",
	LessEqual:         "<=",
	Greater:           ">",
	Less:              "<",
	NotEqual1:         "<>",
	NotEqual2:         "!=",
	NotEqual3:         "<=>",
	AllEqual:          "ALL=",
	AllGreaterEqual:   "ALL>=",
	AllLessEqual:      "ALL<=",
	AllGreater:        "ALL>",
	AllLess:           "ALL<",
	AllNotEqual1:      "ALL<>",
	AllNotEqual2:      "ALL!=",
	AllNotEqual3:      "ALL<=>",
	AnyEqual:          "ANY=",
	AnyGreaterEqual:   "ANY>=",
	AnyLessEqual:      "ANY<=",
	AnyGreater:        "ANY>",
	AnyLess:           "ANY<",
	AnyNotEqual1:      "ANY<>",
	AnyNotEqual2:      "ANY!=",
	AnyNotEqual3:      "ANY<=>",
	SomeEqual:         "SOME=",
	SomeGreaterEqual:  "SOME>=",
	SomeLessEqual:     "SOME<=",
	SomeGreater:       "SOME>",
	SomeLess:          "SOME<",
	SomeNotEqual1:     "SOME<>",
	SomeNotEqual2:     "SOME!=",
	SomeNotEqual3:     "SOME<=>",
	Int:               "int",
	Int8:              "int8",
	Int16:             "int16",
	Int32:             "int32",
	Int64:             "int64",
	Float32:           "float32",
	Float64:           "float64",
	NotBetween:        "not_between",
	Between:           "between",
	NotRegexp:         "not_regexp",
	Regexp:            "regexp",
	Like:              "like",
	NotLike:           "not_like",
	Sum:               "sum",
	Count:             "count",
	Gcount:            "gcount",
	Gsum:              "gsum",
	Len:               "len",
	Deflate:           "deflate",
	DateToStr:         "date_to_str",
	TimeToStr:         "time_to_str",
	String:            "string",
}

type keys struct {
	First, Not, SignalNot, SignalExclamation, SignalAdd, SignalSub, DoubleSub, Add, Sub, Mul, Div, Res, Exist, Is,
	IsNot, In, NotIn, Or, And, Equal, GreaterEqual, LessEqual, Greater, Less, NotEqual1, NotEqual2, NotEqual3, AllEqual,
	AllGreaterEqual, AllLessEqual, AllGreater, AllLess, AllNotEqual1, AllNotEqual2, AllNotEqual3, AnyEqual,
	AnyGreaterEqual, AnyLessEqual, AnyGreater, AnyLess, AnyNotEqual1, AnyNotEqual2, AnyNotEqual3, SomeEqual,
	SomeGreaterEqual, SomeLessEqual, SomeGreater, SomeLess, SomeNotEqual1, SomeNotEqual2, SomeNotEqual3, Int, Float32,
	Float64, NotBetween, Between, NotRegexp, Regexp, Like, NotLike, Sum, Count, Gcount, Gsum, Len, Deflate, DateToStr,
	TimeToStr, String, Int8, Int16, Int32, Int64 string
}
